services:
  streamlit_app:
    build: ./streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
      - stt_service
      - tts_service

  agent_service:
    build: ./multiagent-fin/backend/agent_service
    ports:
      - "8000:8000"
    env_file:
      - .env

  stt_service:
    build: ./multiagent-fin/backend/stt_service
    ports:
      - "8001:8001"

  tts_service:
    build: ./multiagent-fin/backend/tts_service
    ports:
      - "8002:8002"